id: I1A0E00E4
default_language: fr
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:22:18.832650
last_modified: 2023-02-10 00:22:18.832775
source_metadata:
  title: 'Asaṅga/Maitreya: Mahāyānasūtrālaṃkāra'
  language: fr
bases:
  '9144':
    base_file: 9144.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
